---
title: "CountdownTimer"
author: "WinsonYang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(remotes)) install.packages("remotes"); library(remotes)
if (!require(countdown)) install_github("gadenbuie/countdown"); library(countdown)
```

## R Markdown

This is a countdown timer for the exercise

``` {css, echo = FALSE}
#special_timer.running {
  background-color: black;

}
#special_timer.finished {
  background-color: black;

}
#special_timer.running .countdown-digits {
  color: #fdf6e3;
}

```


```{r countdown60, echo = FALSE}
# Get the solarized color palette
countdown(minutes = 1, seconds = 00, 
          warn_when = 20,
          left = 0, right = 1,
          padding = "10px",
          margin = "5%",
          font_size = "12em",
          id = "special_timer")
```

```{r countdown180, echo = FALSE}
# Get the solarized color palette
countdown(minutes = 3, seconds = 00, 
          warn_when = 20,
          left = 0.5, right = 0.5,
          padding = "10px",
          margin = "5%",
          font_size = "12em",
          id = "special_timer")
```

```{r countdown300, echo = FALSE}
# Get the solarized color palette
countdown(minutes = 5, seconds = 00, 
          warn_when = 20,
          left = 1, right = 0,
          padding = "10px",
          margin = "5%",
          font_size = "12em",
          id = "special_timer")
```

